### PR TITLE
fix: typings

### PR DESCRIPTION
**Pull request by scarletsky**

### CODE REVIEW

**Comment by scarletsky** [comment]
@Neoflash1979 Any ideas of this pr ?

**Comment by snowfrogdev** [comment]
@scarletsky Good job. I will merge your changes but know that I am no longer actively maintaining this repo. I encourage you to also submit your changes to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/playcanvas

**Comment by scarletsky** [comment]
@Neoflash1979 Oh, I see. But I am new to typescript, I don't know how to submit my changes to DefinitelyTyped. Maybe just send pull request ? Or other ways ?

**Comment by snowfrogdev** [comment]
@scarletsky yeah, you just have to fork the DefinitelyTyped repo and then submit a pull request. Follow their instructions in their readme file. What is great with DefinitelyTyped is that you can install typings for almost all existing javascript librairies by simply doing `npm install @types/[nameofpackage]`

**Comment by scarletsky** [comment]
Ok, I will do that.

**Pull request merged**
